# Introduction to NumPy

The most fundamental third-party package for scientific computing in Python is NumPy, which provides multidimensional array data types, along with associated functions and methods to manipulate them. Other third-party packages, including Pandas, use NumPy arrays as backends for more specialized data structures.


While Python comes with several container types (`list`,`tuple`,`dict`), NumPy's arrays are implemented closer to the hardware, and are therefore more efficient than the built-in types. This is particularly true for large data, for which NumPy scales much better than Python's built-in data structures.


NumPy arrays also retain a suite of associated functions and methods that allow for efficient *array-oriented* computing.


## Basics of Numpy arrays

We now turn our attention to the Numpy library, which forms the base layer for the entire Python *scientific stack*.  Once you have installed numpy, you can import it as

In [1]:
import numpy

though we will employ the common shorthand

In [2]:
import numpy as np

As mentioned above, the main object provided by numpy is a powerful array.  We'll start by exploring how the numpy array differs from Python lists.  We start by creating a simple list and an array with the same contents of the list:

In [3]:
lst = list(range(1000))
arr = np.arange(1000)

# Here's what the array looks like
arr[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(arr)

numpy.ndarray

In [5]:
%timeit [i**2 for i in lst]

1000 loops, best of 3: 398 µs per loop


In [6]:
%timeit arr**2

The slowest run took 74.38 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 1.48 µs per loop


Elements of a one-dimensional array are indexed with square brackets, as with lists:

In [7]:
arr[5:10]

array([5, 6, 7, 8, 9])

In [10]:
arr[-1]

999

The first difference to note between lists and arrays is that arrays are *homogeneous*; i.e. all elements of an array must be of the same type.  In contrast, lists can contain elements of arbitrary type. For example, we can change the last element in our list above to be a string:

In [11]:
lst[0] = 'a string inside a list'
lst[:10]

['a string inside a list', 1, 2, 3, 4, 5, 6, 7, 8, 9]

but the same can not be done with an array, as we get an error message:

In [12]:
arr[0] = 'a string inside an array'

ValueError: invalid literal for int() with base 10: 'a string inside an array'

The information about the type of an array is contained in its *dtype* attribute:

In [13]:
arr.dtype

dtype('int64')

Once an array has been created, its dtype is fixed and it can only store elements of the same type.  For this example where the dtype is integer, if we store a floating point number it will be automatically converted into an integer:

In [14]:
arr[0] = 1.234
arr[:10]

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Above we created an array from an existing list; now let us now see other ways in which we can create arrays, which we'll illustrate next.  A common need is to have an array initialized with a constant value, and very often this value is 0 or 1 (suitable as starting value for additive and multiplicative loops respectively); `zeros` creates arrays of all zeros, with any desired dtype:

In [15]:
np.zeros(5, float)

array([ 0.,  0.,  0.,  0.,  0.])

In [16]:
np.zeros(3, int)

array([0, 0, 0])

In [17]:
np.zeros(3, complex)

array([ 0.+0.j,  0.+0.j,  0.+0.j])

and similarly for `ones`:

In [18]:
print('5 ones: {0}'.format(np.ones(5)))

5 ones: [ 1.  1.  1.  1.  1.]


If we want an array initialized with an arbitrary value, we can create an empty array and then use the fill method to put the value we want into the array:

In [19]:
a = np.empty(4)
a

array([  3.10503618e+231,   3.10503618e+231,   3.10503618e+231,
         2.78134232e-309])

In [20]:
a.fill(5.5)
a

array([ 5.5,  5.5,  5.5,  5.5])

In [21]:
%timeit np.empty(1000)

The slowest run took 10.68 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 1.01 µs per loop


In [22]:
%timeit np.ones(1000)

The slowest run took 9.40 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 3.28 µs per loop


In [23]:
%timeit np.empty(1000).fill(1)

The slowest run took 16.99 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 1.98 µs per loop


In [24]:
%timeit np.ones(1000)*5.5

The slowest run took 9.80 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 5.28 µs per loop


We have seen how the `arange` function generates an array for a range of integers. Relatedly,  the `linspace` and `logspace` functions to create linearly and logarithmically-spaced grids respectively, with a fixed number of points and including both ends of the specified interval:

In [25]:
np.linspace(0, 1, num=5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [26]:
np.linspace(0, 1, endpoint=False, num=5)

array([ 0. ,  0.2,  0.4,  0.6,  0.8])

In [27]:
np.logspace(1, 4, num=4)

array([    10.,    100.,   1000.,  10000.])

Finally, it is often useful to create arrays with random numbers that follow a specific distribution.  The `np.random` module contains a number of functions that can be used to this effect, for example this will produce an array of 5 random samples taken from a standard normal distribution (0 mean and variance 1):

In [28]:
np.random.randn(5)

array([ 1.82710478, -2.44927766,  1.20854156, -1.21075482,  0.70707842])

whereas this will also give 5 samples, but from a normal distribution with a mean of 9 and a standard deviation of 3:

In [29]:
norm10 = np.random.normal(loc=9, scale=3, size=10)

## Exercises

1. Generate a NumPy array of 1000 random numbers sampled from a Poisson distribution, with parameter `lam=5`. What is the modal value in the sample?

2. Generate a 10 x 10 matrix of standard normal (mean=0, variance=1) random numbers.

In [146]:
# Write your answer here

## Indexing with other arrays

Above we saw how to index arrays with single numbers and slices, just like Python lists.  But arrays allow for a more sophisticated kind of indexing which is very powerful: you can index an array with another array, and in particular with an array of boolean (`bool`) values.  This is particluarly useful to extract information from an array that matches a certain condition.

Consider for example that in the array `norm10` we want to replace all values above 9 with the value 0.  We can do so by first finding the *mask* that indicates where this condition is `True` or `False`:

In [30]:
norm10

array([  1.61405175,  11.80354997,   3.38021683,  12.50534867,
         8.75463536,   5.91852712,   9.83516871,  11.2544392 ,
        13.67320871,  11.9654011 ])

In [31]:
mask = norm10 > 9
mask

array([False,  True, False,  True, False, False,  True,  True,  True,  True], dtype=bool)

Now that we have this mask, we can use it to either read those values or to reset them to 0:

In [32]:
norm10[mask]

array([ 11.80354997,  12.50534867,   9.83516871,  11.2544392 ,
        13.67320871,  11.9654011 ])

In [33]:
norm10[mask] = 0
norm10

array([ 1.61405175,  0.        ,  3.38021683,  0.        ,  8.75463536,
        5.91852712,  0.        ,  0.        ,  0.        ,  0.        ])

## Multidimensional Arrays

Numpy can create arrays of aribtrary dimensions, and all the methods illustrated in the previous section work with more than one dimension. For example, a list of lists can be used to initialize a two dimensional array:

In [35]:
samples_list = [[632, 1638, 569, 115], [433,1130,754,555]]
samples_array = np.array(samples_list)
samples_array.shape

(2, 4)

With two-dimensional arrays we start seeing the power of numpy: while a nested list can be indexed using repeatedly the `[ ]` operator, multidimensional arrays support a much more natural indexing syntax with a single `[ ]` and a set of indices separated by commas:

In [36]:
samples_list[0][1]


1638

In [37]:
samples_array[0,1]

1638

Most of the array creation functions listed above can be used with more than one dimension, for example:

In [38]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [39]:
np.random.normal(10, 3, size=(2, 4))

array([[  6.9432986 ,  10.40795156,  14.10356185,  12.13149235],
       [ 10.6325033 ,  11.19104454,  13.11896649,  14.68728636]])

In fact, the shape of an array can be changed at any time, as long as the total number of elements is unchanged.  For example, if we want a 2x4 array with numbers increasing from 0, the easiest way to create it is via the numpy array's `reshape` method.

In [40]:
arr = np.arange(8).reshape(2,4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

With multidimensional arrays, you can also use slices, and you can mix and match slices and single indices in the different dimensions (using the same array as above):

In [41]:
arr[1, 2:4]

array([6, 7])

In [42]:
arr[:, 2]

array([2, 6])

If you only provide one index, then you will get the corresponding row.

In [43]:
arr[1]

array([4, 5, 6, 7])

Now that we have seen how to create arrays with more than one dimension, it's a good idea to look at some of the most useful properties and methods that arrays have.  The following provide basic information about the size, shape and data in the array:

In [44]:
print('Data type                :', samples_array.dtype)
print('Total number of elements :', samples_array.size)
print('Number of dimensions     :', samples_array.ndim)
print('Shape (dimensionality)   :', samples_array.shape)
print('Memory used (in bytes)   :', samples_array.nbytes)

Data type                : int64
Total number of elements : 8
Number of dimensions     : 2
Shape (dimensionality)   : (2, 4)
Memory used (in bytes)   : 64


Arrays also have many useful methods, some especially useful ones are:

In [46]:
print('Minimum and maximum             :', samples_array.min(), samples_array.max())
print('Sum, mean and standard deviation:', samples_array.sum(), samples_array.mean(), samples_array.std())

Minimum and maximum             : 115 1638
Sum, mean and standard deviation: 5826 728.25 435.545563059


For these methods, the above operations area all computed on all the elements of the array.  But for a multidimensional array, it's possible to do the computation along a single dimension, by passing the `axis` parameter; for example:

In [47]:
samples_array.sum(axis=0)

array([1065, 2768, 1323,  670])

In [48]:
samples_array.sum(axis=1)

array([2954, 2872])

As you can see in this example, the value of the `axis` parameter is the dimension which will be *consumed* once the operation has been carried out.  This is why to sum along the rows we use `axis=0`.  

This can be easily illustrated with an example that has more dimensions; we create an array with 4 dimensions and shape `(3,4,5,6)` and sum along the axis index 2.  That consumes the dimension whose length was 5, leaving us with a new array that has shape `(3,4,6)`:

In [49]:
np.zeros((3,4,5,6)).sum(2).shape

(3, 4, 6)

Another widely used property of arrays is the `.T` attribute, which allows you to access the transpose of the array:

In [50]:
samples_array.T

array([[ 632,  433],
       [1638, 1130],
       [ 569,  754],
       [ 115,  555]])

Which is the equivalent of calling NumPy's `transpose` function:

In [51]:
np.transpose(samples_array)

array([[ 632,  433],
       [1638, 1130],
       [ 569,  754],
       [ 115,  555]])

There is a wide variety of methods and properties of arrays.       

In [52]:
[attr for attr in dir(samples_array) if not attr.startswith('__')]

['T',
 'all',
 'any',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'astype',
 'base',
 'byteswap',
 'choose',
 'clip',
 'compress',
 'conj',
 'conjugate',
 'copy',
 'ctypes',
 'cumprod',
 'cumsum',
 'data',
 'diagonal',
 'dot',
 'dtype',
 'dump',
 'dumps',
 'fill',
 'flags',
 'flat',
 'flatten',
 'getfield',
 'imag',
 'item',
 'itemset',
 'itemsize',
 'max',
 'mean',
 'min',
 'nbytes',
 'ndim',
 'newbyteorder',
 'nonzero',
 'partition',
 'prod',
 'ptp',
 'put',
 'ravel',
 'real',
 'repeat',
 'reshape',
 'resize',
 'round',
 'searchsorted',
 'setfield',
 'setflags',
 'shape',
 'size',
 'sort',
 'squeeze',
 'std',
 'strides',
 'sum',
 'swapaxes',
 'take',
 'tobytes',
 'tofile',
 'tolist',
 'tostring',
 'trace',
 'transpose',
 'var',
 'view']

You can access the documentation for any of them using the `help` function.

In [53]:
help(samples_array.strides)

Help on tuple object:

class tuple(object)
 |  tuple() -> empty tuple
 |  tuple(iterable) -> tuple initialized from iterable's items
 |  
 |  If the argument is a tuple, the return value is the same object.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __getnewargs__(...)
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __le__(self, value, /)
 |      Return self<=value.
 |  
 |  __len__(self, /)
 |      Return len(self).
 |  
 |  __lt__(self, value, /)
 |      Return self<value.
 |  
 |  _

More generally, you can search for NumPy help on a variety of topics, using the `lookfor` function. 

In [54]:
np.lookfor('masked array') 

Search results for 'masked array'
---------------------------------
numpy.ma.array
    An array class with possibly masked values.
numpy.ma.asarray
    Convert the input to a masked array of the given data-type.
numpy.mafromtxt
    Load ASCII data stored in a text file and return a masked array.
numpy.ma.put
    Set storage-indexed locations to corresponding values.
numpy.ma.asanyarray
    Convert the input to a masked array, conserving subclasses.
numpy.ma.diag
    Extract a diagonal or construct a diagonal array.
numpy.ma.dump
    Pickle a masked array to a file.
numpy.ma.isMA
    Test whether input is an instance of MaskedArray.
numpy.ma.masked_all
    Empty masked array with all elements masked.
numpy.ma.count
    Count the non-masked elements of the array along the given axis.
numpy.ma.dumps
    Return a string corresponding to the pickling of a masked array.
numpy.ma.masked_less
    Mask an array where less than a given value.
numpy.ma.mvoid
    Fake a 'void' object to use for ma

## Array Operations

Arrays support all regular arithmetic operators, and the numpy library also contains a complete collection of basic mathematical functions that operate on arrays.  It is important to remember that in general, all operations with arrays are applied *element-wise*, i.e., are applied to all the elements of the array at the same time.  Consider for example:

In [55]:
sample1, sample2 = np.array([632, 1638, 569, 115]), np.array([433,1130,754,555])
sample_sum = sample1 + sample2

print('{0} + {1} = {2}'.format(sample1, sample2, sample_sum))

[ 632 1638  569  115] + [ 433 1130  754  555] = [1065 2768 1323  670]


Importantly, you must remember that even the multiplication operator is by default applied element-wise, it is *not* the matrix multiplication from linear algebra (as is the case in Matlab, for example):

In [56]:
print('{0} X {1} = {2}'.format(sample1, sample2, sample1*sample2))

[ 632 1638  569  115] X [ 433 1130  754  555] = [ 273656 1850940  429026   63825]


While this means that in principle arrays must always match in their dimensionality in order for an operation to be valid, numpy will *broadcast* dimensions when possible.  For example, suppose that you want to add the number 1.5 to `arr1`; the following would be a valid way to do it:

In [109]:
sample1 + 1.5*np.ones(4)

array([  633.5,  1639.5,   570.5,   116.5])

But thanks to numpy's broadcasting rules, the following is equally valid:

In [110]:
sample1 + 1.5

array([  633.5,  1639.5,   570.5,   116.5])

In this case, numpy looked at both operands and saw that the first (`arr1`) was a one-dimensional array of length 4 and the second was a scalar, considered a zero-dimensional object. The broadcasting rules allow numpy to:

* *create* new array of length 1 
* *extend* the array to match the size of the corresponding array

So in the above example, the scalar 1.5 is effectively cast to a 1-dimensional array of length 1, then stretched to length 4 to match the dimension of `arr1`. After this, element-wise addition can proceed as now both operands are one-dimensional arrays of length 4.

This broadcasting behavior is in practice enormously powerful, especially because when numpy broadcasts to create new dimensions or to stretch existing ones, it doesn't actually replicate the data.  In the example above the operation is carried *as if* the 1.5 was a 1-d array with 1.5 in all of its entries, but no actual array was ever created.  This saves memory and improves the performance of operations.

When broadcasting, NumPy compares the sizes of each dimension in each operand. It starts with the trailing dimensions, working forward and creating dimensions as needed to accomodate the operation. Two dimensions are considered compatible when:

* they are equal in size
* one is scalar (or size 1)

If these conditions are not met, an exception is thrown, indicating that the arrays have incompatible shapes. 

In [111]:
sample1 + np.array([7,8])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

Let's create a 1-dimensional array and add it to a 2-dimensional array, to illustrate broadcasting:

In [114]:
b = np.array([10, 20, 30, 40])
bcast_sum = sample1 + b

print('{0}\n\n+ {1}\n{2}\n{3}'.format(sample1, b, '-'*12, bcast_sum))

[ 632 1638  569  115]

+ [10 20 30 40]
------------
[ 642 1658  599  155]


What if we wanted to add `[-100, 100]` to the rows of `sample1`?  Direct addition will not work:

In [115]:
c = np.array([-100, 100])
sample1 + c

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

Remember that matching begins at the trailing dimensions. Here, `c` would need to have a *trailing* dimension of 1 for the broadcasting to work.  Fortunately, we can augment arrays with dimensions on the fly, by indexing it with a `np.newaxis` object:

In [116]:
cplus = c[:, np.newaxis]
cplus

array([[-100],
       [ 100]])

This is exactly what we need, and indeed it works:

In [117]:
sample1 + cplus

array([[ 532, 1538,  469,   15],
       [ 732, 1738,  669,  215]])

For the full broadcasting rules, please see the official Numpy docs, which describe them in detail and with more complex examples.

### Exercises

Generate the following structure as a numpy array, without typing the values by hand. Then, create another array containing just the 2nd and 4th rows.

        [[1,  6, 11],
         [2,  7, 12],
         [3,  8, 13],
         [4,  9, 14],
         [5, 10, 15]]

In [63]:
# Write your answer here

Divide each column of the array:

        a = np.arange(25).reshape(5, 5)

elementwise with the array `b = np.array([1., 5, 10, 15, 20])`.

In [64]:
# Write your answer here

Generate a 10 x 3 array of random numbers (in range [0,1]). For each row, pick the number closest to 0.5.

*Hints*:

* Use `abs` and `argsort` to find the column `j` closest for each row.
* Use "fancy" indexing to extract the numbers.


In [65]:
# Write your answer here

## Linear Algebra

Numpy includes a linear algebra submodule, along with a suite of `array` methods for performing linear algebra. For example, the `dot` method performs an inner (dot) product on vectors and matrices:

In [68]:
v1 = np.array([2, 3, 4])
v2 = np.array([1, 0, 1])

v1.dot(v2)

6

Equivalently, we can use the `dot` function:

In [67]:
np.dot(v1, v2)

6

When performing regular matrix-vector multiplication, note that numpy makes no distinction between row and column vectors and simply verifies that the dimensions match the required rules of matrix multiplication, in this case we have a $2 \times 3$ matrix multiplied by a 3-vector, which produces a 2-vector:

In [69]:
A = np.arange(6).reshape(2, 3)

A.dot(v1)

array([11, 38])

For matrix-matrix multiplication, the same dimension-matching rules must be satisfied, e.g. consider the difference between $A \times A^T$:

In [70]:
A.dot(A.T)

array([[ 5, 14],
       [14, 50]])

and $A^T \times A$:

In [71]:
A.T.dot(A)

array([[ 9, 12, 15],
       [12, 17, 22],
       [15, 22, 29]])

Beyond inner products, the `numpy.linalg` module includes functions for calculating determinants, matrix norms, Cholesky decomposition, eigenvalue and singular value decompositions, and more.  

Additional linear algebra tools are available in SciPy's linear algebra library, `scipy.linalg`. It includes the majority of the tools in the classic LAPACK libraries as well as functions to operate on sparse matrices.  

## Reading and writing data

Numpy lets you save and retrive data structures to and from files on a local or remote storage, in either **text** or **binary** formats. Which format is appropriate depends on the tradeoff that you are willing to make:

* **Text mode**: occupies more space, precision can be lost (if not all digits are written to disk), but is readable and editable by hand with a text editor.  Storage is limited to one- and two-dimensional arrays.

* **Binary mode**: compact and exact representation of the data in memory, can't be read or edited by hand.  Arrays of any size and dimensionality can be saved and read without loss of information.

First, let's see how to read and write arrays in text mode.  The `np.savetxt` function saves an array to a text file, with options to control the precision, separators and even adding a header:

In [72]:
arr = np.arange(10).reshape(2, 5)
np.savetxt('test.out', arr, fmt='%.2e', header="My dataset")

In [73]:
!cat test.out

# My dataset
0.00e+00 1.00e+00 2.00e+00 3.00e+00 4.00e+00
5.00e+00 6.00e+00 7.00e+00 8.00e+00 9.00e+00


And this same type of file can then be read with the matching `np.loadtxt` function:

In [74]:
arr2 = np.loadtxt('test.out')
arr2

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.]])

For binary data, Numpy provides the `np.save` and `np.savez` routines.  The first saves a single array to a file with `.npy` extension, while the latter can be used to save a *group* of arrays into a single file with `.npz` extension.  The files created with these routines can then be read with the `np.load` function.

Let us first see how to use the simpler `np.save` function to save a single array:

In [75]:
np.save('test.npy', arr2)

# Now we read this back
arr2n = np.load('test.npy')

# Let's see if any element is non-zero in the difference.
# A value of True would be a problem.
np.any(arr2 - arr2n)

False

Now let us see how the `np.savez` function works.  You give it a filename and either a sequence of arrays or a set of keywords.  In the first mode, the function will auotmatically name the saved arrays in the archive as `arr_0`, `arr_1`, etc:

In [76]:
np.savez('test.npz', arr, arr2)
arrays = np.load('test.npz')
arrays.files

['arr_1', 'arr_0']

Alternatively, we can explicitly name the arrays we save using keyword arguments for `savez`:

In [77]:
np.savez('test.npz', array1=arr, array2=arr2)
arrays = np.load('test.npz')
arrays.files

['array2', 'array1']

The object returned by `np.load` from an `.npz` file works like a dictionary, though you can also access its constituent files by attribute using its special `.f` field; this is best illustrated with an example with the `arrays` object from above:

In [78]:
# First row of array
arrays['array1'][0]

array([0, 1, 2, 3, 4])

Equivalently:

In [79]:
arrays.f.array1[0]

array([0, 1, 2, 3, 4])

This `.npz` format is a very convenient way to package compactly and without loss of information, into a single file, a group of related arrays that pertain to a specific problem.  At some point, however, the complexity of your dataset may be such that the optimal approach is to use one of the standard formats in scientific data processing that have been designed to handle complex datasets, such as NetCDF or HDF5.  

## Guided Exercise

Import the `microbiome.csv` dataset in the `data` directory using NumPy's `loadtxt` function. This will take some experimentation; use the built-in help to get hints!

In [18]:
# Write answer here

---

In [20]:
from IPython.core.display import HTML
def css_styling():
    styles = open("styles/custom.css", "r").read()
    return HTML(styles)
css_styling()